#! /bin/bash

source ./ceph-cluster-create
source ./ceph-cluster-delete
source ./ceph-cluster-start
source ./ceph-cluster-stop
source ./ceph-cluster-util

function usage {
cat << EndOfUsage
Usage:
	ceph-cluster [create|start|stop|delete|restart]

		create			- builds the Docker base image, starts the containers, install ceph on all the nodes
						and creates the initial configuration of the cluster
		stop			- shutdowns all the container without deleting their contents
		start			- starts all the cluste nodes previously stopped
		delete			- deletes a cluster, all its nodes and any images that existed
		restart			- it does what it says
		install-debs		- on each cluster node install ceph dependencies
		copy-debs <folder>	- given a path where you have build the deb files install them on the nodes
		stop-services		- stop all ceph services on cluster nodes
		start-services		- start all ceph services on cluster nodes

Description:
	ceph-cluster users create a Ceph Cluster hosted entirely on a single machine.
	Cluster nodes are Docker containers that run a full init system, a ssh server and have
	full connectivity between them.

EndOfUsage

}

case $1 in
"create")
	create_cluster;;
"stop")
	stop_cluster;;
"start")
	start_cluster;;
"delete")
	delete_cluster;;
"restart")
	stop_cluster && start_cluster;;
"status")
	echo "Ceph cluster:";
	sudo docker ps ;;
"stop-services")
	ceph_services_stop;;
"start-services")
	ceph_services_start;;
"copy-debs")
	copy_debs $2;;
"install-deps")
	install_dependencies;;
*)
	usage;;
esac
