#! /bin/bash

SERVICE_NAME=ceph-mount-service
FILES_DIR=/home/pis/src/licenta/dev-files
NUM_DISKS=4
NUM_OSD=3
LOGGER="Ceph Docker Disk mounted on"


# create the files that will represent the extra disks for the containers
mkdir $FILES_DIR
num=0
for (( i = 1; i <= $NUM_OSD; i++)); do

	for (( j = 0; j < $NUM_DISKS; j++)); do
		FILE="osd$i-disk$j"
		HOST_FILE="$FILES_DIR/$FILE"

		[ -f $HOST_FILE ]  || fallocate -l 2G $HOST_FILE
		sudo losetup -f $HOST_FILE
		disk=$(losetup --associated $HOST_FILE | cut -f1 -d:)
		devs[$num]=$disk
		((num = $num + 1))
		echo "$LOGGER $disk" | systemd-cat -t $SERVICE_NAME

	done
done


# partition the disks on the OSDs
num=0
for (( i = 1; i <= $NUM_OSD; i++)); do
	for (( j = 0; j < 3 ; j++)); do
		FILE=${devs[$num]} ; ((num++))
		echo "Running mkfs on " $FILE | systemd-cat -t $SERVICE_NAME
		sudo parted -s $FILE mklabel gpt mkpart primary xfs 0% 100%
		sudo mkfs.xfs $FILE -f
	done
	FILE=${devs[$num]} ; ((num++))
	sudo parted -s $FILE mklabel gpt mkpart primary 0% 33% mkpart primary 34% 66% mkpart primary 67% 100%
done


echo "Exited" | systemd-cat -t $SERVICE_NAME
