#! /bin/bash

SERVICE_NAME=ceph-mount-service
NUM_DISKS=4
NUM_OSD=3
NUM_DEVS=$(($NUM_DISKS * $NUM_OSD))
LOGGER="Ceph Docker Disk mounted on"

# retrieve name of loop devices from journalctl
loop_devs=$(journalctl -b | grep "$LOGGER" | tail -n $NUM_DEVS | awk '{print $NF}')

for dev in $loop_devs; do
	sudo losetup -d $dev
	echo "Umounted $dev" | systemd-cat -t $SERVICE_NAME
done

