#! /bin/bash

SERVICE_NAME=ceph-mount-blk
SERVICE_UNIT=$SERVICE_NAME".service"
SERVICE_PATH="/etc/systemd/system/"$SERVICE_NAME".service"
EXEC_PATH="/usr/local/bin"

# move the service unit file to the right place
sudo cp $SERVICE_UNIT $SERVICE_PATH
sudo chmod 664 $SERVICE_PATH

# notify systemd that a new service file exists
systemctl daemon-reload

